export const actionTypes = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  FETCH_ALL: "FETCH_ALL",
  DELETE: "DELETE",
  LIKE: "LIKE",
  AUTH: "AUTH",
  LOGOUT: "LOGOUT",
  FETCH_BY_SEARCH: "FETCH_BY_SEARCH",
  START_LOADING: "START_LOADING",
  END_LOADING: "END_LOADING",
  FETCH_POST: "FETCH_POST",
  COMMENT: "COMMENT",
};
